import { useEffect } from 'react'

// Les données (noms, remarques, contenus saisis) ne sont jamais traduites.
// Seuls les libellés connus de l'interface et leurs attributs d'aide le sont.
const EN = new Map(Object.entries({
  'Déconnexion':'Log out', 'Notifications':'Notifications', 'Tout lire':'Mark all as read',
  'Aucune notification pour le moment.':'No notifications at the moment.',
  'Les demandes RH et alertes scolaires apparaîtront ici.':'HR requests and school alerts will appear here.',
  'Activer':'Enable', 'Actualiser':'Refresh', 'Annuler':'Cancel', 'Enregistrer':'Save',
  'Valider':'Confirm', 'Supprimer':'Delete', 'Modifier':'Edit', 'Fermer':'Close',
  'Semaine':'Week', 'Préparer':'Plan', 'Lectures':'Readings', 'Matériel':'Resources',
  'Enfants':'Children', 'Mon espace RH':'My HR area', 'RH':'HR',
  'Emploi du Temps & Agenda':'Timetable & Calendar', 'Pédagogie & Cours':'Teaching & Lessons',
  'Ma Classe & Évaluations':'My Class & Assessments', 'Discipline':'Discipline',
  'Perfs & Ma Prime':'Performance & Bonus', 'Dossier RH & Demandes':'HR File & Requests',
  'Emploi du temps & Agenda':'Timetable & Calendar', 'Gestion du Personnel':'Staff Management',
  'Pédagogie':'Teaching', 'Synthèse':'Overview', 'Maternelle':'Kindergarten',
  'Mon emploi du temps':'My timetable', 'Programme':'Curriculum', 'Préparations':'Lesson plans',
  'Préparation':'Lesson plan', 'Évaluations':'Assessments', 'Messages Parents (WhatsApp)':'Parent Messages (WhatsApp)',
  'Signalements & Discipline':'Reports & Discipline', 'Mon dossier':'My file', 'Mes demandes':'My requests',
  'Rotation de la semaine A':'Week A rotation', 'Rotation de la semaine B':'Week B rotation',
  'Alternance équilibrée sur deux semaines':'Balanced two-week rotation',
  'Nouvelle préparation':'New lesson plan', 'Classe calculée par rotation :':'Class determined by rotation:',
  '1er trimestre':'Term 1', '2e trimestre':'Term 2', '3e trimestre':'Term 3',
  'Publier la préparation':'Publish lesson plan', 'Séances publiées':'Published lessons',
  'Aucune préparation publiée.':'No lesson plan has been published.',
  'Matériel récupéré et installé en classe':'Resources collected and set up in the classroom',
  'Tout est présent':'Everything is ready', 'Incomplet':'Incomplete', 'Absent':'Missing',
  'Confirmer la lecture et envoyer':'Confirm reading and submit',
  'Alertes d’accompagnement':'Child support alerts', 'Aucune alerte active.':'No active alert.',
  'Je prends en charge maintenant':'I am taking care of this now',
  'Assistante':'Teaching Assistant', 'Maîtresse':'Teacher', 'Français':'French', 'Anglais':'English',
  'Petite Section':'Preschool Class', 'Grande Section':'Reception Class',
  'Objectif':'Objective', 'Objectifs':'Objectives', 'Domaine':'Learning area',
  'Déroulement du cours':'Lesson procedure', 'Matériel nécessaire':'Required resources',
  'Consignes particulières à l’assistante':'Specific instructions for the teaching assistant',
  'Choisir un objectif du référentiel':'Select a curriculum objective',
  'Choisir un objectif officiel':'Select an official objective',
  'Objectif officiel sélectionné':'Selected official objective',
  'Quel est l’objectif principal ?':'What is the main objective?',
  'Quel sera votre rôle pendant l’activité ?':'What will your role be during the activity?',
  'Où récupérer le matériel ?':'Where should the resources be collected?',
  'Difficulté ou risque identifié':'Identified difficulty or risk',
  'Mon profil':'My profile', 'Informations personnelles':'Personal information',
  'Informations professionnelles':'Employment information', 'Documents administratifs':'Administrative documents',
  'Nouvelle demande':'New request', 'Historique':'History', 'Envoyer la demande':'Submit request',
  'Permission':'Leave permission', 'Absence':'Absence', 'Avance de salaire':'Salary advance',
  'Prêt':'Loan', 'Congé Maternité':'Maternity leave', 'Demande d’achat':'Purchase request',
  'Classe':'Class', 'Élève':'Pupil', 'Élèves':'Pupils', 'Matière':'Subject', 'Date':'Date',
  'Heure':'Time', 'Statut':'Status', 'En attente':'Pending', 'Validé':'Approved', 'Refusé':'Declined',
  'Aujourd’hui':'Today', 'Cette semaine':'This week', 'À venir':'Upcoming', 'Terminé':'Completed',
  'Charger':'Load', 'Télécharger':'Download', 'Imprimer':'Print', 'Retour':'Back', 'Suivant':'Next',
  'Précédent':'Previous', 'Rechercher':'Search', 'Aucun résultat':'No results',
  'Chargement…':'Loading…', 'Enregistrement…':'Saving…', 'Envoyer':'Submit',
  'Pointage':'Attendance', 'Stock':'Resources', 'Contrôle maternelle':'Kindergarten checks',
  'Ronde avant la montée des couleurs':'Morning classroom inspection',
  'Tables et bancs rangés':'Tables and benches are tidy', 'Classe propre':'Classroom is clean',
  'Matériel pédagogique rangé':'Teaching resources are stored',
  'Effets personnels rangés':'Personal belongings are organised', 'Passages dégagés':'Walkways are clear',
  'Aucun danger visible':'No visible hazard', 'Assistante responsable':'Teaching assistant responsible',
  'Enregistrer la ronde':'Save inspection', 'Alerte accompagnement enfant':'Child support alert',
  'Choisir l’enfant':'Select the child', 'Ou saisir le nom de l’enfant':'Or enter the child’s name',
  'Normale':'Normal', 'Haute':'High', 'Critique':'Critical', 'Signaler maintenant':'Report now',
  'Pilotage de la maternelle':'Kindergarten monitoring',
  'Préparations, responsabilités et respect des délais':'Lesson plans, responsibilities and deadline compliance',
  'Lues par les assistantes':'Read by teaching assistants', 'Contrôles à temps':'Checks completed on time',
  'Rondes conformes':'Compliant inspections', 'Alertes ouvertes':'Open alerts',
  'Dernières séances':'Latest lessons', 'Rondes et alertes':'Inspections and alerts', 'Clôturer':'Close alert',
  'Brouillon':'Draft', 'Publiée':'Published', 'Réalisée':'Completed', 'Reportée':'Postponed',
}))

// Couverture complète des modules accessibles depuis un compte enseignant ou
// assistante : emploi du temps, pédagogie, classe, bulletins, discipline,
// matériel, performances et dossier RH. Les clés sont des libellés exacts :
// une remarque libre qui contiendrait un mot français n'est donc pas altérée.
Object.entries({
  // Navigation
  'ESPACE ENSEIGNANT':'TEACHER PORTAL', 'Mon Emploi du Temps':'My Timetable',
  'Agenda & Événements':'Calendar & Events', 'Programme & Matières':'Curriculum & Subjects',
  'Préparations à accompagner':'Lesson plans to support', 'Mes préparations':'My lesson plans',
  'Progressions du programme':'Curriculum progress', 'Check-points de fin de leçon':'End-of-lesson checkpoints',
  'Présence & Liste Classe':'Attendance & Class List', 'Devoirs de maison':'Homework',
  'Évaluations & bulletins':'Assessments & Reports', 'Évaluations & bulletin trimestriel':'Assessments & Term Report',
  'Messages parents (WhatsApp)':'Parent messages (WhatsApp)', 'Mon Dossier RH':'My HR File',
  'Demandes & Justificatifs':'Requests & Supporting Documents',

  // Actions et états communs
  'Annuler la modification':'Cancel editing', 'Enregistrer les modifications':'Save changes',
  'Valider et continuer':'Confirm and continue', 'Réessayer':'Try again', 'Arrêter':'Stop',
  'Reprendre depuis le début':'Start again', 'Passer cet enfant':'Skip this pupil',
  'Calcul en cours…':'Calculating…', 'En correction':'Corrections requested', 'À corriger':'Needs correction',
  'Validée':'Approved', 'Approuvée':'Approved', 'Refusée':'Declined', 'Non évalué':'Not assessed',
  'EN COURS':'IN PROGRESS', 'À VENIR':'UPCOMING', 'OFFICIELLE':'OFFICIAL',
  '-- Choisir --':'-- Select --', '— choisir la matière —':'— select a subject —',
  '— Choisir la leçon —':'— select the lesson —', '— autre, à préciser —':'— other, please specify —',

  // Emploi du temps et agenda
  'Semaine précédente':'Previous week', 'Semaine suivante':'Next week', 'Semaine en cours':'Current week',
  'Semaine à venir':'Next week', 'Semaine dernière':'Last week', 'Semaine archivée':'Archived week',
  'Revenir à la semaine en cours':'Return to the current week', 'Horaire':'Time', 'Date et heure':'Date and time',
  'Mon emploi du temps maternelle':'My kindergarten timetable', 'Agenda 2026-2027':'2026–2027 Calendar',
  'Titre':'Title', 'Lieu':'Location', 'Début':'Start', 'Debut':'Start', 'Me rappeler':'Remind me',
  '1 heure avant':'1 hour before', '1 jour avant':'1 day before', '1 semaine avant':'1 week before',
  '15 minutes avant':'15 minutes before', '30 minutes avant':'30 minutes before',
  '＋ Planifier un rappel':'＋ Schedule a reminder', 'Titre de l événement':'Event title',
  'Réunion, documents à préparer…':'Meeting, documents to prepare…',
  'Aucun événement personnel planifié.':'No personal event scheduled.',
  'Fete de l Armee':'Armed Forces Day', 'Journee des Martyrs':'Martyrs’ Day',
  'Lundi de Paques':'Easter Monday', 'Celebration Fin d annee':'End-of-year celebration',
  'Conge Periode 1':'Period 1 break', 'Vacances de Noel':'Christmas holidays',
  'Conge Periode 3':'Period 3 break', 'Conge Periode 4':'Period 4 break',
  'Grandes Vacances':'Summer holidays', 'Reprise des formations des enseignants':'Teacher training resumes',
  'Rentree scolaire 2026-2027':'Start of the 2026–2027 school year', 'Fin des cours':'End of classes',
  'Chargement de votre emploi du temps…':'Loading your timetable…',
  'Aucune matière ne vous est encore affectée.':'No subject has been assigned to you yet.',
  'Aucune matière ne vous est encore affectée sur la plateforme.':'No subject has been assigned to you on the platform yet.',
  'La direction attribue les matières depuis son espace ; votre emploi du temps apparaîtra ici automatiquement.':'The school management assigns subjects from its portal; your timetable will appear here automatically.',

  // Programme et préparation
  'Programme officiel':'Official curriculum', 'PROGRAMME OFFICIEL · MATERNELLE':'OFFICIAL KINDERGARTEN CURRICULUM',
  'PROGRAMME NATIONAL':'NATIONAL CURRICULUM', 'PROGRAMME INTERNATIONAL':'INTERNATIONAL CURRICULUM',
  'Objectifs annuels':'Annual objectives', 'Tous les objectifs de l’année':'All objectives for the year',
  'Sélectionnez une matière pour consulter ses objectifs du premier au troisième trimestre.':'Select a subject to view its objectives from Term 1 to Term 3.',
  'La même source que le bulletin : chaque objectif préparé ici pourra ensuite être évalué, sans double saisie.':'The same source as the report: every objective prepared here can then be assessed without duplicate entry.',
  'Lecture des objectifs…':'Loading objectives…', 'Chargement du programme…':'Loading curriculum…',
  'Aucun programme defini.':'No curriculum defined.', 'Aucun programme défini.':'No curriculum defined.',
  'Aucun objectif':'No objectives', 'Aucun objectif dans votre langue pour ce trimestre.':'No objectives in your language for this term.',
  'Aucune matière renseignée pour ce programme.':'No subject has been entered for this curriculum.',
  'Aucune matière ou aucun objectif ne correspond à votre recherche.':'No subject or objective matches your search.',
  'Rechercher une matière ou un objectif…':'Search for a subject or objective…',
  'Déjà préparés':'Already planned', 'À programmer':'To be scheduled', 'Préparé':'Planned',
  'Soumettre une préparation':'Submit a lesson plan', 'Fichier de préparation':'Lesson plan file',
  'Date du cours':'Lesson date', 'Heure du cours':'Lesson time', 'Matières':'Subjects',
  'Objectif :':'Objective:', 'OBJECTIF ·':'OBJECTIVE ·', 'Domaines d’évaluation':'Assessment areas',
  'Différenciation':'Differentiation', 'Trace écrite':'Written record', 'Durée':'Duration',
  'Enregistrer cette matière':'Save this subject', 'Aucune préparation soumise':'No lesson plan submitted',

  // Circuit assistante
  'Circuit des préparations maternelles':'Kindergarten lesson-plan workflow',
  '1. J’ai lu et compris la préparation':'1. I have read and understood the lesson plan',
  'Ce que j’ai compris du cours':'What I understood about the lesson',
  'Le rôle que je jouerai pendant la séance':'The role I will play during the lesson',
  'Mon apport pour mieux aider les enfants':'My contribution to better support the children',
  'Mettre à jour mon apport':'Update my contribution', 'Valider ma contribution':'Confirm my contribution',
  '2. Je rassemble le matériel':'2. I gather the resources',
  'Une ligne par matériel. Écrivez par exemple « 4 x ardoises ».':'One resource per line. For example, write “4 x slates”.',
  'Matériel indiqué dans la préparation':'Resources listed in the lesson plan',
  'Demander au surveillant':'Request from the supervisor', 'Transmission…':'Submitting…',
  'Matériel de la séance':'Lesson resources', 'Stock insuffisant':'Insufficient stock',
  'Remettre':'Hand over', 'Fourni':'Provided', 'Commandé':'Ordered', 'Indisponible':'Unavailable',
  'Confirmer reçu et installé':'Confirm received and set up', 'Reçu et installé':'Received and set up',
  'À traiter par le surveillant':'Awaiting supervisor action',
  'Transmis au responsable administratif':'Sent to the Administrative Officer',
  'Fourni par l’administration · à remettre':'Provided by administration · ready for handover',
  'Remis à l’assistante · confirmation attendue':'Handed to the teaching assistant · awaiting confirmation',
  'Non fourni':'Not provided', 'Préparation à temps':'Lesson plan submitted on time',
  'Délai plein (heures)':'Full-credit deadline (hours)', 'Délai minimum (heures)':'Minimum deadline (hours)',
  'Lecture et apport':'Reading and contribution', 'Matériel assistante':'Teaching assistant resources',
  'Traitement surveillant':'Supervisor processing', 'Traitement administratif':'Administrative processing',
  'Barème du circuit':'Workflow scoring rules', 'Seule la Direction peut modifier ces valeurs.':'Only the school management can change these values.',
  'Enregistrer le barème':'Save scoring rules', 'Surveillance':'Supervision', 'Administration':'Administration',
  'Action non accomplie à l’échéance :':'Action not completed by the deadline:',
  'Lire, proposer votre apport, demander le matériel puis confirmer son installation.':'Read the lesson plan, propose your contribution, request resources, then confirm they are set up.',
  'Aucune action en attente pour le moment.':'No action is pending at the moment.',
  'Chargement du circuit…':'Loading workflow…',

  // Classe, checkpoints, évaluations
  'Classes':'Classes', 'Ma classe':'My class', 'Liste de classe':'Class list', 'Présence':'Attendance',
  'Choisir la classe':'Select the class', '1. Choisir la classe':'1. Select the class',
  'Choisissez d’abord une classe.':'Select a class first.', 'Aucune classe ne vous est affectée':'No class is assigned to you',
  'Aucune classe maternelle ne vous est affectée.':'No kindergarten class is assigned to you.',
  'Rechercher un élève':'Search for a pupil', 'Rechercher un élève…':'Search for a pupil…',
  'Rechercher un élève ou un matricule…':'Search for a pupil or admission number…',
  'Nom, Prénom, Matricule...':'Surname, first name, admission number…',
  'Saisir nom, prénom ou matricule...':'Enter surname, first name or admission number…',
  'Aucun élève du primaire dans vos classes.':'No primary pupil in your classes.',
  'Aucun élève de Petite ou Grande Section dans vos classes affectées.':'No Preschool or Reception pupil in your assigned classes.',
  'Check-point':'Checkpoint', 'Check-points':'Checkpoints', 'Où en est la classe':'Class progress',
  'Choisissez une préparation validée pour ouvrir son check-point.':'Select an approved lesson plan to open its checkpoint.',
  'Absent — notion à rattraper':'Absent — learning to catch up', 'Participation':'Participation',
  'Compréhension':'Understanding', 'Moyenne':'Average', 'Note':'Score', 'Note obtenue':'Score achieved',
  'Note facultative':'Optional score', 'Enregistrer les check-points':'Save checkpoints',
  'Check-point enregistre ce jour':'Checkpoint saved today',
  'Le nouveau check-point attend sa migration.':'The new checkpoint is awaiting its database update.',
  'Acquis':'Achieved', 'Bien acquis':'Secure', 'Très bien ou bien acquis':'Secure or mastered',
  'À construire ou renforcer':'Developing or needs reinforcement', 'À accompagner':'Needs support',
  'À renforcer':'Needs improvement', 'Assez bien':'Fairly good', 'Passable':'Pass', 'Insuffisant':'Insufficient',
  'Écrit':'Written', 'Oral':'Oral', 'Évaluations orales':'Oral assessments',
  'Moyenne matière':'Subject average', 'Moyenne trimestrielle':'Term average',
  'MOYENNE DU TRIMESTRE':'TERM AVERAGE', 'MATIÈRES ÉVALUÉES':'SUBJECTS ASSESSED',
  'BULLETIN OFFICIEL · PRIMAIRE':'OFFICIAL PRIMARY REPORT', 'PRIMAIRE':'PRIMARY',
  'Écrit et oral sont calculés séparément, puis réunis sans pénaliser une modalité non évaluée.':'Written and oral work are calculated separately, then combined without penalising an unassessed mode.',
  'Aucune note : cette modalité ne comptera pas dans la moyenne.':'No score: this mode will not count towards the average.',
  'Commentaire de l’enseignant':'Teacher’s comment', 'Intitulé de l’évaluation':'Assessment title',
  'Ex. Contrôle 1':'E.g. Test 1', '+ Ajouter une note':'+ Add a score',
  'Imprimer le bulletin':'Print report', 'Voir le bulletin':'View report',

  // Bulletin maternelle
  'BULLETIN MATERNELLE · ÉCOLE INTERNATIONALE BILINGUE':'KINDERGARTEN REPORT · INTERNATIONAL BILINGUAL SCHOOL',
  'BILAN TRIMESTRIEL':'TERM REPORT', 'MATERNELLE':'KINDERGARTEN',
  'Évaluer et raconter les progrès':'Assess and describe progress',
  'Une saisie simple pour l’enseignante, un bulletin clair pour la famille.':'Simple entry for the teacher, a clear report for the family.',
  'objectifs renseignés dans votre langue':'objectives completed in your language',
  'Distinctions et appréciation':'Awards and comments', 'Cette partie vient après la matrice d’évaluation.':'This section follows the assessment matrix.',
  'Appréciation':'Comment', 'Appréciation de l’enseignante':'Teacher’s comment',
  'Développement personnel':'Personal development',
  'Ces cinq repères sont des observations de vie et de maturité. Ils restent distincts du programme scolaire.':'These five indicators are observations of life skills and maturity. They remain separate from the school curriculum.',
  'Le trimestre en un regard':'The term at a glance',
  'Les informations essentielles pour comprendre les progrès de l’enfant.':'Key information for understanding the child’s progress.',
  'Mon chemin de progrès':'My learning journey',
  'Un indicateur d’observation par domaine, sans note académique ni comparaison entre les enfants.':'One observation indicator per learning area, without academic marks or comparison between children.',
  'Progression par matière':'Progress by subject',
  'Chaque carte présente un acquis observé et le prochain petit pas.':'Each card shows an observed achievement and the next small step.',
  'Des idées pour continuer à la maison':'Ideas for continuing at home',
  'Trois actions simples, concrètes et adaptées au prochain petit pas.':'Three simple, practical actions tailored to the next small step.',
  'Les regards croisés de l’équipe':'The team’s combined observations',
  'Les deux langues racontent ensemble les progrès du même enfant.':'Both languages together describe the same child’s progress.',
  'Vie de classe et développement personnel':'Class life and personal development',
  'Des repères essentiels pour comprendre comment l’enfant apprend et grandit.':'Key indicators for understanding how the child learns and grows.',
  'Encouragements et distinctions':'Encouragement and awards',
  'Ce que l’équipe éducative choisit de valoriser ce trimestre.':'What the teaching team has chosen to celebrate this term.',
  'Repères factuels de la période':'Factual indicators for the period',
  'Chaque constat indique sa source. « À accompagner » ouvre un dialogue, jamais une sanction.':'Each observation identifies its source. “Needs support” opens a dialogue; it is never a sanction.',
  'Lecture partagée':'Shared review',
  'On valorise les points d’appui et on décrit le contexte avant toute conclusion.':'We celebrate strengths and describe the context before drawing any conclusion.',
  'Plan d’action école-famille':'School–family action plan',
  'Des engagements simples, datés et partagés, avec une aide proposée par l’école.':'Simple, dated, shared commitments, with support offered by the school.',
  'Grandir avec les autres':'Growing with others',
  'Cinq repères de développement personnel observés au quotidien.':'Five personal-development indicators observed every day.',
  'Impression et soumission réservées à la titulaire de la section.':'Printing and submission are restricted to the class teacher.',
  'Chargement des bulletins maternelle…':'Loading kindergarten reports…',
  'Rien d’enregistré sur ce trimestre.':'Nothing has been recorded for this term.',
  'Observation à compléter.':'Observation to be completed.',

  // Devoirs et documents
  'Devoir':'Homework', 'Devoirs':'Homework', 'Nouveau devoir':'New homework', 'Type de devoir':'Homework type',
  'À rendre':'Due', 'À rendre pour le':'Due on', 'Énoncé':'Instructions', 'ÉNONCÉ ·':'INSTRUCTIONS ·',
  'Barème':'Marking scheme', 'BARÈME ·':'MARKING SCHEME ·', 'Fiches jointes':'Attached worksheets',
  'Élèves concernés *':'Pupils concerned *', 'Toute la classe':'Whole class', 'Choisir des élèves':'Select pupils',
  'Aucun devoir enregistré pour l’instant.':'No homework has been recorded yet.',
  'Aucun devoir enregistré pour cette classe.':'No homework has been recorded for this class.',
  'Aucun devoir n’est coché.':'No homework is selected.', 'Informer les parents':'Inform parents',
  'Via le WhatsApp officiel de l’école':'Via the school’s official WhatsApp account',
  'Responsable(s) au dossier':'Registered parent(s) / guardian(s)',
  'Devoir donné par':'Homework set by', 'Visa du parent':'Parent’s signature', 'Visa de la direction':'School management’s signature',
  'APPRÉCIATION DE L’ENSEIGNANT':'TEACHER’S COMMENT', 'Communiqué lors de la correction.':'Provided when the work is marked.',
  'PROGRAMME PÉDAGOGIQUE • DEVOIRS DE MAISON':'CURRICULUM • HOMEWORK',

  // Messages et discipline
  'Messages parents':'Parent messages', 'Type de message':'Message type', 'Composer le message':'Write the message',
  'Votre message':'Your message', 'Écrivez votre message ici…':'Write your message here…',
  'Aperçu et envoi':'Preview and send', 'Informer le parent':'Inform the parent',
  'Comportement exemplaire ✓':'Excellent behaviour ✓', 'Nature du comportement':'Nature of behaviour',
  'Gravité':'Severity', 'Mineure':'Minor', 'Modéré':'Moderate', 'Grave':'Serious', 'Critique':'Critical',
  'Mesure appliquée':'Action taken', 'Aucune mesure':'No action', 'Avertissement verbal':'Verbal warning',
  'Avertissement écrit':'Written warning', 'Convocation des parents':'Parent meeting',
  'Suspension temporaire':'Temporary suspension', 'Perturbation du cours':'Disrupting the lesson',
  'Refus de travailler':'Refusal to work', 'Irrespect envers l’enseignant':'Disrespect towards the teacher',
  'Propos inappropriés':'Inappropriate language', 'Bagarre':'Fighting',
  'Signaler un incident':'Report an incident', 'Signaler un incident concernant un élève':'Report an incident concerning a pupil',
  'Classe concernée *':'Class concerned *', 'Élève concerné *':'Pupil concerned *',
  'Gravité constatée *':'Observed severity *', 'Description précise de l’incident *':'Detailed description of the incident *',
  'Description précise':'Detailed description', 'Décrivez précisément les faits…':'Describe the facts precisely…',
  'Décrivez les faits observés, le lieu et l’heure approximative…':'Describe the observed facts, location and approximate time…',
  'Le surveillant recevra le signalement et sera le seul à appliquer la punition.':'The supervisor will receive the report and will be solely responsible for applying any sanction.',
  'Incident signalé au surveillant !':'Incident reported to the supervisor!',
  'en classe':'in the classroom', 'dans la cour':'in the playground', 'dans le couloir':'in the corridor',
  'en récréation':'during break', 'à la cantine':'in the canteen',

  // Matériel
  'Demande de matériel':'Resource request', 'Demander du matériel':'Request resources',
  'Suivi du stock et demandes de matériel':'Stock monitoring and resource requests',
  'Intitulé du matériel demandé *':'Requested resource *', 'Quantité souhaitée':'Quantity required',
  'Coût estimé (FCFA)':'Estimated cost (FCFA)', 'Degré d’urgence':'Urgency level',
  'Faible (Planifié)':'Low (planned)', 'Moyen (Besoin courant)':'Medium (routine need)',
  'Urgent (Bloquant pour le cours)':'Urgent (lesson cannot proceed)', 'Envoyer la demande':'Submit request',

  // Dossier RH, demandes et performances
  'Demandes, Prêts & Justificatifs RH':'HR Requests, Loans & Supporting Documents',
  'Mes Demandes Soumises':'My Submitted Requests', 'Nouvelle Demande':'New Request',
  'Choisissez le type de demande *':'Select the request type *', 'Demande de Prêt':'Loan Request',
  'Avance sur Salaire':'Salary Advance', "Justificatif d'Absence":'Absence Documentation',
  "Permission d'Absence":'Leave Request', 'Détails de la Demande de Prêt':'Loan Request Details',
  'Détails de la Demande d’Avance sur Salaire':'Salary Advance Request Details',
  'Montant du prêt souhaité (FCFA) *':'Requested loan amount (FCFA) *',
  'Montant de l’avance (FCFA) *':'Advance amount (FCFA) *', 'Remboursement':'Repayment',
  'Mois de paie concerné':'Relevant payroll month',
  'Justification d’une Absence Passée ou à Venir':'Supporting Information for a Past or Upcoming Absence',
  'Date début d’absence *':'Absence start date *', 'Date fin d’absence *':'Absence end date *',
  'Nature de la permission':'Type of leave', 'Absence ponctuelle (1 jour)':'One-day absence',
  'Absence de quelques heures':'A few hours’ absence', 'Événement familial (Mariage, Naissance...)':'Family event (wedding, birth, etc.)',
  'Collègue':'Colleague', 'Pièce justificative (Certificat médical, convocation...) *':'Supporting document (medical certificate, summons, etc.) *',
  'Expliquez brièvement les raisons de votre demande à l’attention de la Direction...':'Briefly explain the reasons for your request to the school management…',
  'En attente de validation':'Awaiting approval', 'Réponse de la Direction / Comptabilité :':'School Management / Accounts response:',
  'Aucune demande soumise pour le moment.':'No request has been submitted yet.',
  'Vous n’avez encore rien demandé.':'You have not submitted any request yet.',
  'Complétude Dossier':'File completeness', 'Prénom(s) *':'First name(s) *',
  'Nom de famille *':'Surname *', 'Genre':'Gender', 'Masculin':'Male', 'Féminin':'Female',
  'Date de naissance *':'Date of birth *', 'Lieu de naissance':'Place of birth', 'Nationalité':'Nationality',
  'Situation matrimoniale':'Marital status', 'Célibataire':'Single', 'Marié(e)':'Married',
  'Divorcé(e)':'Divorced', 'Veuf/Veuve':'Widowed', '+ Ajouter un enfant':'+ Add a child',
  'Aucun enfant à charge enregistré.':'No dependants recorded.', 'Nom & Prénom enfant':'Child’s full name',
  'Âge (ans)':'Age (years)', 'Classe / Niveau scolaire':'Class / School level', 'Élève à IDEAL ?':'Pupil at IDEAL?',
  'Oui':'Yes', 'Non':'No', 'Adresse de résidence complète *':'Full home address *',
  'Téléphone principal *':'Main phone number *', 'Numéro WhatsApp':'WhatsApp number',
  'Personne à prévenir en cas d’urgence':'Emergency contact', 'Nom & Prénom du contact *':'Contact’s full name *',
  'Lien de parenté':'Relationship', 'Téléphone d’urgence *':'Emergency phone number *',
  'Intitulé du poste':'Job title', 'Spécialité / Discipline':'Specialism / Subject',
  'Date de prise de service à l’école':'Employment start date', 'Type de contrat de travail':'Employment contract type',
  'CDI (Contrat Durée Indéterminée)':'Permanent contract', 'CDD (Contrat Durée Déterminée)':'Fixed-term contract',
  'Vacataire / Prestataire':'Contractor / Service provider', 'Stagiaire':'Intern',
  'Dernier diplôme obtenu *':'Highest qualification *', 'Baccalauréat':'Baccalaureate / A-level equivalent',
  'Licence LMD':'Bachelor’s degree', 'Master / DEA':'Master’s degree', 'Doctorat':'Doctorate',
  'Numéro INPS / Sécurité Sociale':'INPS / Social Security number', 'Mode de paiement souhaité *':'Preferred payment method *',
  'Espèces (Paiement en Caisse)':'Cash (paid at the office)', 'Virement bancaire':'Bank transfer',
  'Nom de la Banque':'Bank name', 'N° de Compte / RIB (IBAN)':'Account number / IBAN',
  'Contrat de Travail':'Employment Contract', 'Dernier Diplôme / Attestation':'Latest Diploma / Certificate',
  'Signature de l’Employé(e)':'Employee signature', 'Le Directeur Général / DRH':'Managing Director / HR Manager',
  'Imprimer la Fiche RH (PDF)':'Print HR File (PDF)', 'Ma prime d’été':'My summer bonus',
  'Ma Prime d’été':'My Summer Bonus', 'Mes avantages':'My benefits', 'Mes Performances':'My Performance',
  'Mes Performances Enseignant':'My Teaching Performance', 'GAGNÉ À CE JOUR':'EARNED TO DATE',
  'MES VACANCES GAGNÉES':'MY EARNED LEAVE', 'Prime non calculable pour l’instant':'Bonus cannot be calculated at the moment',
  'Assiduité, dépôts des fiches de préparation et points de prime cumulés.':'Attendance, lesson-plan submissions and accumulated bonus points.',

  // Libellés détaillés des formulaires et des livrables
  'moyenne de l’écrit et de l’oral lorsqu’ils existent ; sinon, seule la modalité évaluée compte.':'average of written and oral work when available; otherwise only the assessed mode counts.',
  'moyenne des contrôles écrits, chaque note étant ramenée sur 20.':'average of written assessments, with each score converted to a mark out of 20.',
  'moyenne des matières effectivement évaluées.':'average of subjects actually assessed.',
  'moyenne des évaluations orales, chaque note étant ramenée sur 20.':'average of oral assessments, with each score converted to a mark out of 20.',
  '· numéro absent du dossier':'· no phone number in the file', '(ce que l’élève doit faire)':'(what the pupil must do)',
  '+ Soumettre':'+ Submit', '-- Sélectionnez un élève --':'-- Select a pupil --',
  '1. Classe concernée *':'1. Class concerned *', '2. Élève concerné *':'2. Pupil concerned *',
  '3. Gravité constatée *':'3. Observed severity *', '4. Aperçu et envoi':'4. Preview and send',
  '4. Description précise de l’incident *':'4. Detailed description of the incident *',
  'Acquis repérés':'Observed achievements', 'Activités :':'Activities:', 'Adresse Email':'Email address',
  'ASSIDUITÉ':'ATTENDANCE', 'Aucune action particulière définie pour cette période.':'No specific action has been defined for this period.',
  '. Le directeur les notera sur 20 avec des commentaires.':'. The Headteacher will score them out of 20 and add comments.',
  '5 mois (20 SA - 2ème Trimestre)':'5 months (20 weeks – 2nd trimester)',
  '7 mois (28 SA - 3ème Trimestre)':'7 months (28 weeks – 3rd trimester)',
  'Cette fiche soutient le dialogue. Elle n’affecte jamais les résultats ou les droits de l’enfant.':'This sheet supports dialogue. It never affects the child’s results or rights.',
  'Cette matière est visible dans le bulletin commun, mais seul l’enseignant qui en a l’affectation peut la renseigner.':'This subject appears in the shared report, but only the teacher assigned to it can enter results.',
  'Chaque jauge correspond à une moyenne de matière, sur 20.':'Each gauge represents a subject average out of 20.',
  'Choisissez un repère seulement à partir de faits constatés pendant la période.':'Select an indicator only from facts observed during the period.',
  'Classe / Niveau':'Class / Level', 'Clé de lecture':'How to read this report', 'Contexte partagé':'Shared context',
  'Critique / sécurité immédiate':'Critical / immediate safety concern',
  'Date & Lieu de Naissance:':'Date & Place of Birth:', "Date de prise de service à l'école":'Employment start date',
  "Date début d'absence *":'Absence start date *', 'Date début de congé (Pré-natal - 6 sem) *':'Leave start date (antenatal – 6 weeks) *',
  "Date fin d'absence *":'Absence end date *', "Date Présumée d'Accouchement (DPA) *":'Expected delivery date *',
  'Date prévue *':'Scheduled date *', 'Date reprise de service (Post-natal) *':'Return-to-work date (postnatal) *',
  "Degré d'urgence":'Urgency level', 'Dossier Validé à':'File Approved at',
  'Droit de réponse / situation particulière':'Right of reply / special circumstances',
  'Des faits, du contexte et des actions partagées. Cette fiche n’attribue aucune note aux parents et n’affecte jamais les résultats de l’enfant.':'Facts, context and shared actions. This sheet does not score parents and never affects the child’s results.',
  'ENSEIGNANT(E) · FRANÇAIS':'TEACHER · FRENCH', 'Enseignante · Français':'Teacher · French',
  'Envoyer à la Direction':'Submit to the School Management', 'Exécutez une fois':'Run once',
  'La ligne « scolarité » est visible uniquement par le Responsable administratif et la Direction ; aucun montant ne figure sur la version familiale.':'The tuition line is visible only to the Administrative Officer and School Management; no amount appears on the family copy.',
  'La situation de scolarité est réservée au Responsable administratif et à la Direction. Aucun montant n’apparaît dans le bulletin familial.':'Tuition status is restricted to the Administrative Officer and School Management. No amount appears on the family report.',
  'La synthèse commune des observations françaises et anglaises.':'Combined summary of French and English observations.',
  'Les résultats restent compréhensibles, même lorsqu’une matière n’utilise qu’une modalité.':'Results remain clear even when a subject uses only one assessment mode.',
  "Ma prime d'été":'My summer bonus', 'Nationalité:':'Nationality:',
  'Nom & Prénom Enfant':'Child’s full name',
  'Note ramenée sur 20 → moyenne des écrits et moyenne des oraux → moyenne des modalités disponibles → moyenne générale des matières évaluées.':'Score converted to 20 → written average and oral average → average of available modes → overall average of assessed subjects.',
  'Objectif du devoir':'Homework objective', 'Observations encadrées':'Guided observations',
  'Parent / tuteur · date':'Parent / guardian · date', 'Partenariat famille-école':'School–family partnership',
  'Point fort':'Strength', 'Profil pédagogique':'Learning profile', 'Repères alimentés automatiquement':'Indicators filled automatically',
  "Rien d'enregistré sur ce trimestre.":'Nothing has been recorded for this term.',
  'Règle de calcul affichée aux familles':'Calculation rule shown to families',
  'Réglementation République du Mali (INPS & Code du Travail) :':'Republic of Mali regulations (INPS & Labour Code):',
  "Signature de l'Employé(e)":'Employee signature', 'Signature et cachet':'Signature and stamp',
  'Soumettez vos préparations avant':'Submit your lesson plans before', 'Séquences et leçons':'Sequences and lessons',
  'préparés':'planned', 'Suivi bienveillant':'Supportive follow-up',
  'toutes langues réunies':'across both languages', 'Très bien':'Excellent',
  "Téléphone d'urgence *":'Emergency phone number *',
  'Une lecture immédiate des moyennes trimestrielles déjà disponibles.':'An immediate overview of available term averages.',
  "Utilisez l'onglet « ➕ Nouvelle Demande » pour soumettre un prêt, une avance ou une permission.":'Use the “➕ New Request” tab to submit a loan, advance or leave request.',
  "Visa & Cachet de l'Établissement":'School signature & stamp', '« Lu et certifié exact »':'“Read and certified correct”',
  'À IMPRIMER :':'TO PRINT:', 'À l’heure prévue':'On time', 'Âge':'Age', 'École · date':'School · date',
  'Élève IDEAL':'IDEAL pupil', 'Évolution de l’année':'Progress over the year',
  '← Retour':'← Back', '← Retour aux matières':'← Back to subjects',
  '✓ Transmis à l’école':'✓ Sent to the school', "Ma Prime d'été":'My Summer Bonus',
  "Justification d'une Absence Passée ou à Venir":'Supporting Information for a Past or Upcoming Absence',
  '— de 20 000 à 150 000, par tranches de 5 000':'— from 20,000 to 150,000 in increments of 5,000',
  'Vos élèves n’ont pas pu être chargés':'Your pupils could not be loaded',
  "Vos élèves n'ont pas pu être chargés":'Your pupils could not be loaded', 'Évaluer':'Assess',
  'Transmis à l’école':'Sent to the school', 'Diplôme le plus élevé:':'Highest qualification:',
  'Spécialité:':'Specialism:', 'Congé maternité: Du':'Maternity leave: From',
  'Date de permission:':'Leave date:', 'Période d’absence: Du':'Absence period: From',
  'Historique & Suivi de vos Demandes':'Request History & Tracking',
  'Demande de Permission ou Congé Ponctuel':'Leave or Short Absence Request',
  "Demande d'Achat de Matériel Pédagogique":'Teaching Resource Purchase Request',
  'Imprimer Liste Classe':'Print Class List', 'Famille-école':'School–family partnership',
  "Pièce d'Identité (CNI / NINA)":'Identity Document (ID / NINA)',

  // Notifications et messages techniques
  'Centre de Notifications IDEAL':'IDEAL Notification Centre',
  'Autoriser les notifications système sur cet appareil ?':'Allow system notifications on this device?',
  'Cliquez sur une alerte pour ouvrir le module concerné':'Select an alert to open the relevant module',
  'Les notifications sont activées, même lorsque l’application est fermée.':'Notifications are enabled, even when the app is closed.',
  'Notifications activées sur cet appareil.':'Notifications enabled on this device.',
  'Les notifications push ne sont pas supportées par ce navigateur.':'Push notifications are not supported by this browser.',
  'Les notifications nécessitent la version sécurisée HTTPS de l’application.':'Notifications require the secure HTTPS version of the app.',
  'Ce navigateur ne prend pas en charge les notifications en arrière-plan.':'This browser does not support background notifications.',
  'La permission a été refusée. Autorisez les notifications dans les réglages du navigateur.':'Permission was denied. Allow notifications in your browser settings.',
  'À l’instant':'Just now', 'Donnée indisponible — le chargement a échoué':'Data unavailable — loading failed',
  'Votre compte n’a pas accès à cette action.':'Your account does not have access to this action.',
  'L’action n’a pas pu être terminée.':'The action could not be completed.',
  'Action enregistrée et tracée.':'Action saved and logged.', 'Erreur':'Error', 'Erreur:':'Error:',

  // Dates
  'Janvier':'January', 'Février':'February', 'Mars':'March', 'Avril':'April', 'Mai':'May', 'Juin':'June',
  'Juillet':'July', 'Août':'August', 'Aout':'August', 'Septembre':'September', 'Octobre':'October',
  'Novembre':'November', 'Décembre':'December', 'Lundi':'Monday', 'Mardi':'Tuesday', 'Mercredi':'Wednesday',
  'Jeudi':'Thursday', 'Vendredi':'Friday', 'Samedi':'Saturday', 'Dimanche':'Sunday',
}).forEach(([fr, en]) => EN.set(fr, en))

Object.entries({
  // Textes dynamiques et fenêtres propres aux comptes enseignants
  '— numéro absent du dossier':'— no phone number in the file',
  '« Cette semaine » ou « Tout sélectionner » au-dessus de la liste.':'“This week” or “Select all” above the list.',
  '[matière]':'[subject]', '[Votre message ici]':'[Your message here]', '↩ Présent':'↩ Present',
  '▸ Choisir':'▸ Select', 'Nouvel incident à traiter':'New incident to review',
  'Votre demande a été transmise à la Direction Générale et à la Comptabilité avec succès !':'Your request was successfully sent to the School Management and Accounts office!',
  '✓ Préparé':'✓ Planned', 'Demande d’Avance sur Salaire':'Salary Advance Request',
  "Demande d'Avance sur Salaire":'Salary Advance Request', 'Enregistrer le check-point':'Save checkpoint',
  'Sauvegarder mon Dossier':'Save my File', 'Sauvegarder mon Dossier RH':'Save my HR File',
  'Bulletin maternelle à signer':'Kindergarten report awaiting signature', 'Demande de Permission':'Leave Request',
  'Soumettre la préparation':'Submit lesson plan', 'Achat de Matériel Pédagogique':'Teaching Resource Purchase',
  'Livrée':'Delivered', 'Nouvelle demande de matériel':'New resource request',
  'Transmettre la Demande à la Direction':'Submit Request to the School Management',
  'À améliorer':'Needs improvement', 'À compléter avec la famille pendant l’échange…':'To be completed with the family during the meeting…',
  'À compléter avec la famille.':'To be completed with the family.', 'À consolider':'To be reinforced',
  'À renseigner par vous':'To be completed by you', 'Accompagnement à renforcer':'Additional support needed',
  'Action concrète':'Practical action', 'affectations de matières':'subject assignments',
  'Ajouter un devoir de maison':'Add homework', 'Arrivée à l’école à l’heure':'Arrival at school on time',
  'Aucun contexte renseigné.':'No context provided.',
  'Aucun cours préparé pour cette classe parmi vos 60 derniers. Le devoir reste libre.':'No lesson has been prepared for this class among your 60 most recent plans. The homework can remain unlinked.',
  'Aucun départ renseigné':'No departure recorded', 'Aucun élève dans cette classe.':'No pupils in this class.',
  'Aucun élève ne correspond à cette recherche.':'No pupil matches this search.', 'Aucun pointage':'No attendance record',
  'Aucune absence':'No absence', 'Aucune correction demandée.':'No corrections requested.',
  'Aucune de vos préparations n’attend de correction. ✓':'None of your lesson plans needs correction. ✓',
  'Aucune feuille jointe':'No worksheet attached', 'Aucune préparation déposée pour le moment.':'No lesson plan has been submitted yet.',
  'barème des points':'points scoring rules', 'Bulletin soumis ; la notification Direction doit être vérifiée.':'Report submitted; the School Management notification must be checked.',
  'Bulletin soumis à la Direction pour signature.':'Report submitted to the School Management for signature.',
  'Ce que l’élève doit savoir faire après ce devoir…':'What the pupil should be able to do after this homework…',
  'Ce que la famille fait déjà régulièrement…':'What the family already does regularly…',
  'Ce qui a bloqué (repris dans le rapport aux parents)':'What caused difficulty (included in the parent report)',
  'cette matière':'this subject', 'Chaque note doit être comprise entre 0 et son barème.':'Each score must be between 0 and its maximum mark.',
  'Chaque progrès compte':'Every step forward matters', 'Chargement de la prime impossible':'Unable to load bonus',
  'Chargement du bulletin…':'Loading report…', 'Chargement impossible. Réessayez dans un instant.':'Unable to load. Please try again shortly.',
  'Choisir l’élève':'Select the pupil', 'Choisir la section':'Select the section',
  'Choisissez une classe, un élève et décrivez précisément l’incident.':'Select a class and pupil, then describe the incident precisely.',
  'Choisissez une préparation validée.':'Select an approved lesson plan.', 'Clarté des objectifs':'Clarity of objectives',
  'classe non renseignée':'class not specified', "Clé déposée à l'heure":'Key returned on time',
  'Cliquez pour préparer cette séance':'Select to prepare this lesson',
  'Cochez les devoirs à imprimer, ou utilisez « Aujourd’hui »,':'Select the homework to print, or use “Today”,',
  'Commentaire à compléter.':'Comment to be completed.', 'Comptabilité · privé':'Accounts · private',
  'Contrôle de soi':'Self-control', 'Coopération et empathie':'Cooperation and empathy',
  'Créativité':'Creativity', 'Curiosité':'Curiosity', 'Dans les délais':'On time',
  'Demande RH':'HR request', 'Demande transmise au surveillant ✓':'Request sent to the supervisor ✓',
  'Demander à l’enfant de raconter sa journée en trois phrases.':'Ask the child to describe their day in three sentences.',
  'Données partagées':'Shared data', 'Échéance':'Due date', 'Échéancier de scolarité':'Tuition payment schedule',
  'Échec de sauvegarde':'Save failed', 'École':'School', 'École + famille':'School + family',
  'Écoute, partage, aide et travaille avec les autres.':'Listens, shares, helps and works with others.',
  'Enregistrer le devoir':'Save homework', 'Erreur lors de la sauvegarde du dossier.':'An error occurred while saving the file.',
  'Essaie, recommence et va au bout d’une activité.':'Tries, starts again and completes an activity.',
  'Évaluation enregistrée et intégrée au bulletin commun.':'Assessment saved and included in the shared report.',
  'Évaluation prévue':'Scheduled assessment', 'Évaluations écrites':'Written assessments',
  'Évaluez chaque élève ou marquez-le absent.':'Assess each pupil or mark them absent.',
  'Événement enregistré.':'Event saved.', 'Événement supprimé.':'Event deleted.',
  'Ex : Lecture, Mathématiques...':'E.g. Reading, Mathematics…', 'Ex: Bamako, Ségou, Sikasso...':'E.g. Bamako, Ségou, Sikasso…',
  'Ex: CP1, 6ème, Lycée...':'E.g. Grade 1, Year 7, High School…', 'Ex: Époux(se), Frère, Père...':'E.g. spouse, sibling, father…',
  'Ex: Faladiè Sema, Rue 144, Porte 25, Bamako':'E.g. Faladiè Sema, Street 144, Door 25, Bamako',
  'Ex: Rames de papier A4, Boîtes de craie blanche, Kit de géométrie géant...':'E.g. reams of A4 paper, boxes of white chalk, large geometry kit…',
  'Exercice 1 : 10 · Propreté : 5…':'Exercise 1: 10 · Presentation: 5…',
  "Expliquez brièvement les raisons de votre demande à l'attention de la Direction...":'Briefly explain the reasons for your request to the School Management…',
  'FAMILLE - ÉCOLE':'FAMILY – SCHOOL', 'français':'French', 'FRANÇAIS':'FRENCH',
  'Gère progressivement ses émotions et ses impulsions.':'Gradually manages emotions and impulses.',
  'grille normale, telle qu’écrite dans le document.':'standard timetable as set out in the official document.',
  'Hors délai':'Late', 'Hygiène et tenue adaptées':'Appropriate hygiene and clothing',
  'IDEAL École':'IDEAL School', 'IDEAL École Internationale Bilingue':'IDEAL International Bilingual School',
  'Il reste sur cet appareil. Signalez-le à la direction.':'It remains on this device. Inform the School Management.',
  'Indiquez la matière concernée.':'Enter the relevant subject.', "Intitulé de l'évaluation":'Assessment title',
  "L'action n'a pas pu être terminée.":'The action could not be completed.',
  "L'emploi du temps n'est pas encore installé sur la plateforme.":'The timetable has not yet been installed on the platform.',
  'La fiche famille-école doit être installée avec le script SQL dédié.':'The school–family sheet must be installed using its dedicated SQL script.',
  'La quantité doit être supérieure à zéro.':'The quantity must be greater than zero.',
  'La sauvegarde serveur des bulletins doit être installée avec le script SQL dédié.':'Server storage for reports must be installed using its dedicated SQL script.',
  'La sauvegarde serveur du bulletin primaire doit être installée avec sql/bulletins_primaire.sql.':'Server storage for primary reports must be installed with sql/bulletins_primaire.sql.',
  'Le barème du circuit maternelle a été mis à jour.':'The kindergarten workflow scoring rules were updated.',
  'Le circuit doit être installé dans Supabase avec le script sql/circuit_assistantes_maternelle.sql.':'The workflow must be installed in Supabase using sql/circuit_assistantes_maternelle.sql.',
  'Le programme n’a pas encore commencé.':'The curriculum has not started yet.',
  'Les acquis observés sont très solides. Votre enfant mobilise ses compétences avec aisance et régularité.':'Observed achievement is very strong. Your child applies skills confidently and consistently.',
  'Les apprentissages sont bien engagés. Votre enfant progresse de façon régulière dans les domaines travaillés.':'Learning is progressing well. Your child is making steady progress in the areas covered.',
  'les blocs du matin et de l’après-midi sont permutés cette semaine.':'morning and afternoon blocks are swapped this week.',
  'Les compétences se construisent progressivement. Les encouragements et la pratique l’aideront à les consolider.':'Skills are developing progressively. Encouragement and practice will help to reinforce them.',
  'Les observations de la période ne sont pas encore assez complètes pour établir une synthèse.':'There are not yet enough observations for the period to produce a summary.',
  'Maîtrise très solide':'Very secure mastery', 'Matières du bulletin':'Report subjects',
  'Matières enseignées et commentées en français.':'Subjects taught and commented on in French.',
  'MES PROGRÈS':'MY PROGRESS', 'Méthodes & activités':'Methods & activities',
  'Modification refusée :':'Update refused:', 'Modifier ce devoir de maison':'Edit this homework',
  'Modifier le rappel':'Edit reminder', 'Nom':'Surname', 'Non évaluée':'Not assessed', 'Non renseigné':'Not provided',
  'Observation de l’équipe':'Team observation', 'Observation encadrée':'Guided observation',
  'Outils pédagogiques rangés':'Teaching resources put away', 'Pas encore évalué':'Not yet assessed',
  'Persévérance':'Perseverance', 'Persévérance et confiance':'Perseverance and confidence',
  'Pièce justificative':'Supporting document', 'Plusieurs apprentissages demandent encore un accompagnement attentif et des occasions régulières de s’exercer.':'Several areas still require attentive support and regular opportunities to practise.',
  'Prénom':'First name', 'Préparation enregistrée. Le directeur va la corriger.':'Lesson plan saved. The Headteacher will review it.',
  'préparations':'lesson plans', 'Prochaine étape · mot outil':'Next step · key word', 'Prochaine leçon':'Next lesson',
  'PROGRAMME NATIONAL · FRANÇAIS':'NATIONAL CURRICULUM · FRENCH', 'Programme national malien':'Malian national curriculum',
  'Qualité du contenu':'Quality of content', 'Régulier':'Consistent',
  'Remettre le matériel disponible ou transmettre le manque à l’administration.':'Hand over available resources or report missing items to administration.',
  'Répondre aux besoins que le magasin ne peut pas couvrir.':'Respond to needs that the storeroom cannot cover.',
  'Réservé à l’administration':'Restricted to administration', 'Respect et responsabilité':'Respect and responsibility',
  'Respecte les règles, les personnes et le matériel.':'Respects rules, people and resources.',
  'Résultats':'Results', 'Retrait de l’enfant à l’heure':'Child collected on time',
  'Salle fermée à clé':'Classroom locked', 'Sauvegardé':'Saved', 'Sélectionnez une classe.':'Select a class.',
  'Semaine archivée — consultation seule':'Archived week — view only',
  'Seule la maîtresse titulaire de cette section peut soumettre le bulletin.':'Only the class teacher for this section can submit the report.',
  'signalé':'reported', 'Signalement enregistré':'Report saved',
  'Signalement enregistré et transmis au surveillant. Il décidera de la sanction.':'Report saved and sent to the supervisor, who will decide on any sanction.',
  'Signalement enregistré, mais la notification au surveillant a échoué. Prévenez-le directement.':'Report saved, but the supervisor notification failed. Inform the supervisor directly.',
  'Soumission avant H-10 — préparation acceptée.':'Submitted before H-10 — lesson plan accepted.',
  'Suivi':'Follow-up', 'Suivi sauvegardé':'Follow-up saved',
  'Suivre chaque maillon et régler le barème validé.':'Monitor each stage and manage the approved scoring rules.',
  'Suppression refusée :':'Deletion refused:', 'Supprimer cet enfant':'Delete this child',
  'Supprimer cet événement personnel ?':'Delete this personal event?', 'Tables-bancs bien rangés':'Desks and benches tidy',
  'Tout décocher':'Clear all', 'Tout sélectionner':'Select all',
  'Transport, santé, organisation familiale ou autre explication utile…':'Transport, health, family arrangements or other useful explanation…',
  'Très bien acquis':'Mastered', 'Trier des objets puis expliquer le critère choisi.':'Sort objects, then explain the chosen criterion.',
  'Type, matière, objectif, énoncé, barème, date de remise, élèves et pièces jointes':'Type, subject, objective, instructions, marking scheme, due date, pupils and attachments',
  'un avertissement écrit':'a written warning', 'Un message concret, encourageant et utile à la famille…':'A practical, encouraging and useful message for the family…',
  'Un point précis à consolider ensemble…':'One specific point to reinforce together…',
  "Une erreur s'est produite lors de l'envoi de la demande.":'An error occurred while sending the request.',
  'Une observation concrète : acquis, progrès et prochain point à travailler…':'A specific observation: achievement, progress and the next point to work on…',
  'Ventilateur éteint':'Fan switched off',
  'Vos changements remplacent le devoir existant — aucun doublon n’est créé.':'Your changes replace the existing homework — no duplicate is created.',
  'Vos cours, les plus récents d’abord. La matière du devoir n’est pas modifiée par ce choix.':'Your lessons, most recent first. This choice does not change the homework subject.',
  "Votre compte n'a pas accès à cette action.":'Your account does not have access to this action.',
  "Votre dossier n'a pas été enregistré sur le serveur :":'Your file was not saved on the server:',
  'Votre lecture et votre apport ont été enregistrés.':'Your reading and contribution were saved.',
}).forEach(([fr, en]) => EN.set(fr, en))

// Libellés composés et écrans historiques. Certains de ces écrans ont été
// intégrés avant le portail bilingue et utilisent encore des fragments JSX :
// ils doivent pourtant être aussi homogènes que les écrans récents.
Object.entries({
  // Devoirs, cours et messagerie familles
  'ÉLÈVES DE LA CLASSE DE':'PUPILS IN THE CLASS OF',
  'Pour corriger : ouvrez la séance du':'To make corrections: open the lesson dated',
  'Cochez au moins un devoir avant d’imprimer':'Select at least one homework item before printing',
  'la sélection':'the selection', 'Cours associé':'Linked lesson',
  'Aucune matière ne vous est affectée pour cette classe. La direction doit la renseigner.':'No subject has been assigned to you for this class. The School Management must assign one.',
  'Vos cours préparés n’ont pas pu être lus. Le devoir reste enregistrable sans cours associé.':'Your prepared lessons could not be loaded. You can still save the homework without linking it to a lesson.',
  'Énoncé du devoir':'Homework instructions', 'Les exercices, les consignes, les questions…':'Exercises, instructions, questions…',
  'Remise le':'Due on', 'Toute la classe (':'Whole class (',
  'Les fiches porteront automatiquement le nom de chaque élève concerné.':'Each sheet will automatically display the name of the pupil concerned.',
  '• Sans date de remise':'• No due date', '⏰ Pour le':'⏰ Due on',
  'Exercices de maison du cours':'Homework exercises for the lesson',
  'Le message arrive au':'The message is sent to', ', puis l’école le transmet aux parents.':', then the school forwards it to the parents.',
  'Chargement de vos élèves…':'Loading your pupils…',
  "Cette liste est vide parce que la lecture a échoué, pas parce que vous n'avez pas d'élèves.":'This list is empty because loading failed, not because you have no pupils.',
  'Les affectations sont définies par la direction. Signalez-le si cela vous semble erroné.':'Assignments are set by the School Management. Please report anything that appears incorrect.',
  'cette classe':'this class',
  "⚠️ Aucun responsable rattaché à cet élève. Son dossier d'inscription n'est pas lié — l'école devra identifier le destinataire.":'⚠️ No parent or guardian is linked to this pupil. The enrolment file is not connected, so the school will need to identify the recipient.',
  '3. Composer le message':'3. Write the message',
  'a perturbé le déroulement du cours':'disrupted the lesson',
  'a fait preuve d’irrespect envers l’enseignant':'showed disrespect towards the teacher',
  'a été impliqué(e) dans une bagarre':'was involved in a fight',
  'a tenu des propos inappropriés':'used inappropriate language',
  'a adopté un comportement exemplaire':'demonstrated exemplary behaviour',
  'un avertissement verbal':'a verbal warning', 'une retenue':'a detention',
  'une convocation des parents':'a meeting with the parents', 'une suspension temporaire':'a temporary suspension',
  'WhatsApp a été ouvert avec le message préparé. IDEAL ne peut pas confirmer que le parent l’a reçu : l’école reste l’émetteur officiel.':'WhatsApp was opened with the prepared message. IDEAL cannot confirm that the parent received it; the school remains the official sender.',
  'Préparé — pas encore transmis. Le message partira vers le numéro officiel de l’école, jamais depuis votre numéro personnel.':'Prepared — not yet sent. The message will go through the school’s official number, never your personal number.',
  'Joignez un fichier PDF ou une image.':'Attach a PDF file or image.',
  'Erreur upload :':'Upload error:', 'Cliquez pour choisir un fichier':'Select a file',
  'Envoi en cours...':'Uploading…', 'Correction par le directeur':'Headteacher feedback',

  // Agenda, progression et checkpoints
  'Fin le':'Ends on', 'Hors annee scolaire':'Outside the school year',
  'Choisissez d’abord une classe.':'Select a class first.',
  'Check-point de fin de leçon —':'End-of-lesson checkpoint —',
  'Préparation validée dont les séquences sont terminées':'Approved lesson plan with all sessions completed',
  'Cliquez sur une séance pour préparer votre cours. La pastille verte signale celles qui sont déjà prêtes cette semaine. Les cases vides sont vos heures libres : récréations (10h00, 15h00) et déjeuner (12h00) n’y figurent pas, ce ne sont pas des heures d’enseignement.':'Select a lesson to prepare it. The green dot marks lessons already prepared this week. Empty slots are free periods; breaks (10:00, 15:00) and lunch (12:00) are not teaching periods and are not shown.',
  'Volets du programme':'Curriculum sections', 'Voir la ressource':'View resource',
  'Aucun manuel n\'est enregistré pour':'No textbook is registered for',
  '. Les préparations de cette matière restent libres, et l\'avancement se lit dans les préparations déposées.':'. Lesson plans for this subject remain flexible, and progress is based on submitted lesson plans.',
  "C'est elle qui sera proposée dès que vous choisirez cette ressource dans une préparation de":'It will be suggested whenever you select this resource in a lesson plan for',
  "C'est elle qui sera proposée par défaut à votre prochaine préparation de":'It will be suggested by default in your next lesson plan for',
  'se lit dans les préparations déposées : aucun manuel n\'est rattaché à cette matière.':'is measured through submitted lesson plans: no textbook is linked to this subject.',
  'Aucun objectif enregistré pour':'No objective registered for',
  "Les objectifs se déposent avec la planification de période. Tant qu'aucune planification n'en porte pour cette matière, cette liste reste vide — ce qui ne veut pas dire que la matière n'a pas d'objectifs.":'Objectives are added through term planning. Until a plan includes objectives for this subject, this list remains empty; this does not mean the subject has no objectives.',
  "Une leçon est marquée traitée dès qu'une fiche de préparation la vise. Le compte de séquences est celui des demi-heures réellement préparées.":'A lesson is marked as covered as soon as a lesson plan refers to it. The session count reflects the half-hour periods actually prepared.',
  'La progression se suit dans vos préparations : aucun manuel n\'est rattaché à':'Progress is tracked through your lesson plans: no textbook is linked to',
  'Aucune ressource enregistrée pour':'No resource registered for',
  '· programme annuel':'· annual curriculum', 'objectifs à atteindre avant la fin de l’année.':'objectives to achieve by the end of the year.',

  // Performance et prime
  'saisies de la direction':'School Management entries', 'fiches de fin de cours':'end-of-lesson records',
  'emploi du temps':'timetable', 'Ce n’est pas un montant nul.':'This is not a zero amount.',
  'Aucun montant n’est affiché tant que toutes les sources n’ont pas répondu : un total calculé sur des données partielles serait inférieur au vôtre.':'No amount is displayed until all sources have responded, because a total based on partial data would understate what you are owed.',
  'Si le problème persiste, signalez-le à la direction.':'If the problem persists, report it to the School Management.',
  'Mes points ·':'My points ·',
  'Touchez un trimestre, puis un indicateur, pour voir le détail de ce qui a été compté.':'Select a term, then an indicator, to see exactly what was counted.',
  'Hors période de classe : montants du prochain trimestre.':'Outside term time: amounts for the next term.',
  'Ancienneté : — · votre fiche de rémunération n’a pas pu être lue. Les bourses qui en dépendent ne sont pas vérifiables ici pour l’instant.':'Length of service: — · your pay record could not be loaded. Related allowances cannot currently be verified here.',

  // Dossier RH et demandes
  '🔒 Vos données sont confidentielles et sécurisées par la Direction Générale.':'🔒 Your information is confidential and secured by the Executive Management.',
  'Votre dossier RH a été sauvegardé avec succès !':'Your HR file was saved successfully!',
  'Situation Familiale & Enfants du Personnel':'Family Situation & Staff Children',
  'Aucun enfant renseigné pour le moment. Cliquez sur le bouton « + Ajouter un enfant » pour saisir le prénom, l\'âge et la classe de vos enfants.':'No child has been entered yet. Select “+ Add a child” to enter your children’s first name, age and class.',
  'Ex: Enseignement Bilingue Anglais/FR':'E.g. English/French bilingual teaching',
  'FICHE INDIVIDUELLE DU DOSSIER RH':'INDIVIDUAL HR RECORD', 'Fait à Bamako, le':'Issued in Bamako on',
  'Portail enseignant':'Teacher portal',
  'Réessayez, et prévenez la direction si cela se reproduit.':'Try again and inform the School Management if this happens again.',
  "Soumettez vos demandes de prêt, avance de salaire, permissions, justificatifs d'absence ou achats de matériel en toute simplicité.":'Submit loan, salary advance, leave, absence evidence or resource purchase requests.',
  '1. Choisissez le type de demande *':'1. Select the request type *',
  "💵 Détails de la Demande d'Avance sur Salaire":'💵 Salary Advance Request Details',
  "L'avance est déduite en une fois sur votre salaire, à la fin du mois.":'The advance is deducted from your salary in one payment at the end of the month.',
  "Votre salaire n'est pas encore enregistré : la plateforme ne peut pas vérifier le plafond de la moitié. La direction le contrôlera à la main.":'Your salary has not yet been recorded, so the platform cannot verify the 50% limit. The School Management will check it manually.',
  '🤰 Déclaration & Demande de Congé de Maternité (Code du Travail du Mali - Art. L.179)':'🤰 Maternity Leave Declaration & Request (Mali Labour Code — Art. L.179)',
  'Stade actuel de la grossesse *':'Current stage of pregnancy *',
  '— 6 semaines pré-natales (-42 jours avant la DPA) + 8 semaines post-natales (+56 jours après la DPA).':'— 6 weeks before birth (-42 days before the due date) + 8 weeks after birth (+56 days after the due date).',
  "📄 Importer la fiche d'échographie / Déclaration médicale de grossesse *":'📄 Upload ultrasound report / medical pregnancy declaration *',
  'Motif détaillé / Explication de la demande *':'Detailed reason / Explanation of the request *',
  '⏳ Transmission en cours...':'⏳ Submitting…', 'Demande(s) au total':'Total request(s)', 'Soumis le':'Submitted on',
  'Membre du personnel':'Staff member',

  // Ressources et circuit assistante
  '⏳ En attente du surveillant':'⏳ Awaiting supervisor action',
  'Les demandes de matériel ne sont pas encore installées. Le script sql/stock_et_sanctions.sql doit être exécuté une fois dans Supabase.':'Resource requests are not installed yet. The sql/stock_et_sanctions.sql script must be run once in Supabase.',
  'Pour la classe':'For the class', 'Pour les exercices d’écriture du CP1':'For Grade 1 writing exercises',
  'Mes demandes ·':'My requests ·', 'Demandé le':'Requested on', 'remis sur':'handed over out of',

  // Documents de devoirs
  'Un PDF ne s’imprime pas depuis cette page : ouvrez-le et imprimez-le à part.':'A PDF cannot be printed from this page. Open it and print it separately.',
  'Remis le':'Due on',
  'Veuillez accompagner votre enfant durant 20 minutes chaque soir et signer son cahier une fois les exercices terminés.':'Please support your child for 20 minutes each evening and sign the exercise book once the work is complete.',
  'Aucun devoir enregistré pour':'No homework recorded for', '. Ajoutez-en un avant d’imprimer.':'. Add one before printing.',
  'à préparer · un par enfant':'to prepare · one per child',
  'Chaque message part vers le WhatsApp officiel de l’école (':'Each message is sent to the school’s official WhatsApp (',
  '), qui le transmet à la famille. Aucun numéro de parent n’apparaît, et deux familles ne se voient jamais.':'), which forwards it to the family. No parent phone number is shown, and families never see one another.',
  'Aucun enfant concerné par les devoirs sélectionnés.':'No pupil is included in the selected homework.',
  '👥 Toute la classe — préparer les':'👥 Whole class — prepare', '📤 Ouvrir le message pour':'📤 Open the message for',
  'un enfant en particulier':'one specific child', '📤 Message pour':'📤 Message for',

  // Bulletins maternelle et primaire
  'S’organise, range et demande de l’aide au bon moment.':'Organises themselves, tidies up and asks for help at the right time.',
  'Famille':'Family', 'Sauvegarde du suivi…':'Saving follow-up…',
  'MON PORTRAIT D’APPRENTISSAGE':'MY LEARNING PORTRAIT',
  'domaines évalués sur la période · Indicateur visuel : TB 100 % · B 75 % · M 50 % · AR 25 %. Sans classement ni effet automatique sur le passage.':'areas assessed during the term · Visual indicator: EX 100% · GD 75% · DV 50% · NS 25%. No ranking and no automatic effect on progression.',
  'POUR LA SUITE':'NEXT STEPS', 'Inventer un petit parcours et nommer chaque mouvement.':'Create a short movement course and name each movement.',
  'absence(s) sur la période':'absence(s) during the term', 'ENSEIGNANTE · FRANÇAIS':'TEACHER · FRENCH',
  'ENSEIGNANTE · ANGLAIS':'TEACHER · ENGLISH', 'DIRECTION':'SCHOOL MANAGEMENT',
  '· Parent / tuteur : __________________':'· Parent / guardian: __________________',
  'La famille peut expliquer un contexte, corriger un fait ou demander un accompagnement.':'The family may explain circumstances, correct a fact or request support.',
  'Validation du dialogue':'Meeting acknowledgement', 'En cours de consolidation':'Developing',
  'DES APPRENTISSAGES':'LEARNING', 'Autre enseignant':'Other teacher',
  '· Ce bulletin rend compte des apprentissages observés pendant la période. Une case vide signifie « non évalué », jamais zéro.':'· This report reflects learning observed during the term. A blank box means “not assessed”, never zero.',

  // Circuit et aide contextuelle
  'h d’avance, puis retrait d’un point par heure jusqu’au seuil de':'hours in advance, then one point is deducted per hour down to the threshold of',
  'h. Sous ce seuil, la préparation vaut 0 et les rubriques de l’assistante sont neutralisées. Le dernier maillon non accompli porte la responsabilité.':'hours. Below this threshold, the lesson plan scores 0 and the assistant sections are not counted. Responsibility falls on the final incomplete step.',
  'dans':'in', 'dans Supabase.':'in Supabase.', 'sur':'out of', 'Sur':'Out of',
  'devoir':'homework', 'matière(s)':'subject(s)', 'en cours':'in progress', 'En cours':'In progress',
  "Choisissez d'abord une classe.":'Select a class first.', '✓ Les':'✓ All',
}).forEach(([fr, en]) => EN.set(fr, en))

const PHRASES = [
  [/^ESPACE ENSEIGNANT\s*[•·]\s*/i, 'TEACHER PORTAL · '],
  [/Il y a (\d+) min/g, '$1 min ago'], [/Il y a (\d+)h/g, '$1h ago'],
  [/^Il y a (\d+) semaines?$/, '$1 weeks ago'], [/^Dans (\d+) semaines?$/, 'In $1 weeks'],
  [/non lue\(s\)/g, 'unread'], [/Classe calculée par rotation\s*:/g, 'Class determined by rotation:'],
  [/Choisir un objectif officiel \((\d+)\)/g, 'Select an official objective ($1)'],
  [/Le référentiel Supabase est également synchronisé\s*:/g, 'The Supabase curriculum is also synchronised:'],
  [/(\d+) objectif\(s\) disponible\(s\)/g, '$1 objective(s) available'],
  [/(\d+) objectif\(s\) renseigné\(s\) dans votre langue/g, '$1 objective(s) completed in your language'],
  [/^(\d+) préparation\(s\)$/, '$1 lesson plan(s)'], [/^(\d+) demande\(s\) RH$/, '$1 HR request(s)'],
  [/^Message (\d+) sur (\d+)$/, 'Message $1 of $2'],
  [/^Ouvrir le message pour (.+)$/, 'Open the message for $1'], [/^Message pour (.+)$/, 'Message for $1'],
  [/^Soumettez vos préparations avant (.+)$/, 'Submit your lesson plans before $1'],
  [/Assistante\s*:/g, 'Teaching assistant:'], [/Contrôle maîtresse\s*:/g, 'Teacher check:'],
  [/^Matériel\s*:/, 'Resources:'], [/^Objectif\s*:/, 'Objective:'], [/^Statut\s*:/, 'Status:'],
  [/^Stock\s*:/, 'Stock:'], [/^Surveillant\s*:/, 'Supervisor:'],
  [/lecture en attente/g, 'reading pending'], [/en attente/g, 'pending'],
  [/à temps/g, 'on time'], [/hors délai/g, 'late'], [/lu le/g, 'read on'],
  [/^(\d+) demande(s?) transmise(s?) au surveillant\.$/, '$1 request$2 sent to the supervisor.'],
  [/^(\d+) disponible\(s\)$/, '$1 available'], [/^Date non précisée$/, 'Date not specified'],
  [/^Page (\d+) \/ (\d+)$/, 'Page $1 / $2'], [/^Sur (\d+)$/, 'Out of $1'],
  [/^Élève\s*:/, 'Pupil:'], [/^Classe\s*:/, 'Class:'], [/^Matière\s*:/, 'Subject:'],
  [/^Enseignante?\s*:/, 'Teacher:'], [/^À rendre\s*:/, 'Due:'], [/^Barème\s*:/, 'Marking scheme:'],
  [/^Erreur\s*:\s*/i, 'Error: '], [/^Chargement impossible\s*:\s*/i, 'Unable to load: '],
  [/^Enregistrement refusé\s*:\s*/i, 'Save refused: '], [/^Enregistrement impossible\s*:\s*/i, 'Unable to save: '],
  [/^Suppression impossible\s*:\s*/i, 'Unable to delete: '], [/^Modification impossible\s*:\s*/i, 'Unable to update: '],
  [/^Demande non enregistrée\s*:\s*/i, 'Request not saved: '], [/^Demande non transmise\s*:\s*/i, 'Request not sent: '],
  [/^Incident non enregistré\s*:\s*/i, 'Incident not saved: '], [/^Affectation refusée\s*:\s*/i, 'Assignment refused: '],
  [/^Votre demande n'a pas pu être transmise\s*:\s*/i, 'Your request could not be sent: '],
  [/^Supprimer le devoir de (.+) du (.+) \?/, 'Delete the $1 homework due $2?'],
  [/^Cette action est définitive\.$/, 'This action cannot be undone.'],
  [/^Aucun devoir n’est coché\./, 'No homework is selected.'],
  [/^cours du\s+/i, 'lesson on '], [/^Pour le\s+/i, 'Due on '],
  [/^Remise le\s+/i, 'Due on '], [/^Soumis le\s+/i, 'Submitted on '],
  [/^Demandé le\s+/i, 'Requested on '], [/^Fait à Bamako, le\s+/i, 'Issued in Bamako on '],
  [/\blundi\b/gi, 'Monday'], [/\bmardi\b/gi, 'Tuesday'], [/\bmercredi\b/gi, 'Wednesday'],
  [/\bjeudi\b/gi, 'Thursday'], [/\bvendredi\b/gi, 'Friday'], [/\bsamedi\b/gi, 'Saturday'],
  [/\bdimanche\b/gi, 'Sunday'],
  [/\blun\./gi, 'Mon'], [/\bmar\./gi, 'Tue'], [/\bmer\./gi, 'Wed'],
  [/\bjeu\./gi, 'Thu'], [/\bven\./gi, 'Fri'], [/\bsam\./gi, 'Sat'], [/\bdim\./gi, 'Sun'],
  [/\bjanv\./gi, 'Jan'], [/\bfévr\./gi, 'Feb'], [/\bavr\./gi, 'Apr'],
  [/\bjuill\./gi, 'Jul'], [/\bsept\./gi, 'Sep'], [/\boct\./gi, 'Oct'],
  [/\bnov\./gi, 'Nov'], [/\bdéc\./gi, 'Dec'],
  [/\bjanvier\b/gi, 'January'], [/\bfévrier\b/gi, 'February'], [/\bmars\b/gi, 'March'],
  [/\bavril\b/gi, 'April'], [/\bmai\b/gi, 'May'], [/\bjuin\b/gi, 'June'],
  [/\bjuillet\b/gi, 'July'], [/\baoût\b/gi, 'August'], [/\bseptembre\b/gi, 'September'],
  [/\boctobre\b/gi, 'October'], [/\bnovembre\b/gi, 'November'], [/\bdécembre\b/gi, 'December'],
]

export const traduireInterface = value => {
  const brut = String(value || '')
  const avant = brut.match(/^\s*/)?.[0] || ''
  const apres = brut.match(/\s*$/)?.[0] || ''
  const coeur = brut.trim()
  if (!coeur) return brut
  let resultat = EN.get(coeur) || coeur
  // Beaucoup de boutons placent leur pictogramme dans le même nœud texte que
  // le libellé ("📘 Programme & Matières"). Le pictogramme reste identique,
  // seul le libellé qui le suit doit être traduit.
  if (resultat === coeur) {
    const avecIcone = coeur.match(/^([\p{Extended_Pictographic}\uFE0F\u200D\s]+)(.+)$/u)
    if (avecIcone && EN.has(avecIcone[2])) resultat = `${avecIcone[1]}${EN.get(avecIcone[2])}`
  }
  if (resultat === coeur) PHRASES.forEach(([pattern, remplacement]) => { resultat = resultat.replace(pattern, remplacement) })
  return avant + resultat + apres
}

const ATTRS = ['placeholder', 'title', 'aria-label']

function traduireNoeud(node) {
  if (node.nodeType === Node.TEXT_NODE) {
    const parent = node.parentElement
    if (!parent || ['SCRIPT','STYLE','TEXTAREA'].includes(parent.tagName)) return
    const valeur = traduireInterface(node.nodeValue)
    if (valeur !== node.nodeValue) node.nodeValue = valeur
    return
  }
  if (node.nodeType !== Node.ELEMENT_NODE) return
  ATTRS.forEach(attr => {
    if (node.hasAttribute(attr)) {
      const valeur = traduireInterface(node.getAttribute(attr))
      if (valeur !== node.getAttribute(attr)) node.setAttribute(attr, valeur)
    }
  })
  if (node.tagName === 'INPUT' && ['button','submit','reset'].includes(node.type)) node.value = traduireInterface(node.value)
  node.childNodes.forEach(traduireNoeud)
}

export const posteEnAnglais = user => {
  const poste = String(user?.fonction || '').toLowerCase()
  return user?.langue === 'en' || /-(en|english)-/.test(`-${poste}-`) || poste.includes('anglais')
}

export function useEnglishInterface(active) {
  useEffect(() => {
    document.documentElement.lang = active ? 'en' : 'fr'
    if (!active) return undefined
    const appliquer = () => traduireNoeud(document.body)
    appliquer()

    // Les boîtes du navigateur ne créent aucun nœud dans la page. Elles
    // échappaient donc à la traduction et affichaient encore erreurs et
    // confirmations en français au milieu d'une interface anglaise.
    const alertOriginal = window.alert
    const confirmOriginal = window.confirm
    const promptOriginal = window.prompt
    window.alert = message => alertOriginal.call(window, traduireInterface(message))
    window.confirm = message => confirmOriginal.call(window, traduireInterface(message))
    window.prompt = (message, valeur) => promptOriginal.call(window, traduireInterface(message), valeur)

    const observer = new MutationObserver(mutations => mutations.forEach(m => {
      if (m.type === 'characterData') traduireNoeud(m.target)
      if (m.type === 'attributes') traduireNoeud(m.target)
      m.addedNodes.forEach(traduireNoeud)
    }))
    observer.observe(document.body, {
      childList:true, subtree:true, characterData:true,
      attributes:true, attributeFilter:ATTRS,
    })
    return () => {
      observer.disconnect()
      window.alert = alertOriginal
      window.confirm = confirmOriginal
      window.prompt = promptOriginal
    }
  }, [active])
}
